version: "3.7"

services:
  flask-api:
    image: medtrainer/flask-api
    container_name: flask-api
    build:
      context: .
      dockerfile: docker/python/Dockerfile
      target: dev
    ports:
      - 5000:5000
    networks:
      - flask-api
    env_file:
      - .env.dist

networks:
  flask-api:
    name: flask-api
