version: "3.7"

services:
  flask-api:
    image: medtrainer/flask-api:dev
    container_name: flask-api
    build:
      target: dev
    volumes:
      - .:/app
    ports:
      - 5678:5678
    environment:
      - FLASK_DEBUG=1
      - ENVIRONMENT=development
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]

