version: "3.7"

services:
  flask-api:
    image: medtrainer/flask-api:test
    container_name: flask-api
    build:
      target: test
    environment:
      - ENVIRONMENT=test
    entrypoint: ["python", "-m", "pytest"]
